# Generated by Django 5.1 on 2024-09-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_documents_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentspermissions',
            old_name='users',
            new_name='user',
        ),
    ]
