# Generated by Django 5.1 on 2024-09-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_rename_users_documentspermissions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='users',
        ),
        migrations.DeleteModel(
            name='DocumentsPermissions',
        ),
    ]
